USE [portal_admix]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_CALCULA_PROXIMO_DIA_UTIL]    Script Date: 04/11/2014 11:26:55 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_CALCULA_PROXIMO_DIA_UTIL](
	@DT_IN DATETIME
	, @QT_DIAS_SOMAR INT
)
RETURNS DATETIME
AS
BEGIN


DECLARE @DT_RESULTADO DATETIME
DECLARE @NR_DIA_SEMANA INT
DECLARE @FL_RESULTADO BIT 
 
SET @FL_RESULTADO = 0
SET @DT_RESULTADO = DATEADD(D,@QT_DIAS_SOMAR,@DT_IN)
SET @NR_DIA_SEMANA = DATEPART(DW,@DT_RESULTADO)

WHILE @FL_RESULTADO = 0
BEGIN
	IF @DT_IN IS NOT NULL
	BEGIN
		IF (@NR_DIA_SEMANA BETWEEN 2 AND 6)
		BEGIN
			IF (SELECT COUNT(*) FROM AD_FERIADO WHERE DIA = DATEPART(D,@DT_RESULTADO) AND MES = DATEPART(M,@DT_RESULTADO) AND ISNULL(ANO,DATEPART(YY,@DT_RESULTADO)) = DATEPART(YY,@DT_RESULTADO)) = 0
			BEGIN
				SET @FL_RESULTADO = 1
			END
			ELSE
			BEGIN
				SET @DT_RESULTADO = DATEADD(D,1,@DT_RESULTADO)
				SET @NR_DIA_SEMANA = DATEPART(DW,@DT_RESULTADO)
			END
		END	 
		ELSE 
		BEGIN
			SET @DT_RESULTADO = DATEADD(D,1,@DT_RESULTADO)
			SET @NR_DIA_SEMANA = DATEPART(DW,@DT_RESULTADO)
		END
	END
END

IF @DT_RESULTADO = 0
BEGIN
	SET @DT_RESULTADO = NULL
END

RETURN @DT_RESULTADO

END
	

GO


