USE [DB_ADMIX_IN]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_CALCULA_QTDE_DIAS_MES]    Script Date: 04/11/2014 11:09:25 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


CREATE  FUNCTION [dbo].[FN_CALCULA_QTDE_DIAS_MES] (@DATE VARCHAR (6))

RETURNS INT    
AS    
BEGIN

DECLARE @RESULT INT 
DECLARE @DATA_IN VARCHAR(6)
DECLARE @DATA_DATE DATETIME

SET @DATA_IN = @DATE
SET @DATA_DATE = @DATA_IN + '01'

SET @RESULT = DATEDIFF(DD, @DATA_DATE, DATEADD(MM, 1, @DATA_DATE))

RETURN @RESULT

END
GO


