USE [portal_admix]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_GET_ALPHANUMERIC_FROM_STRING]    Script Date: 04/11/2014 11:45:09 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE FUNCTION [dbo].[FN_GET_ALPHANUMERIC_FROM_STRING](@TEXTO VARCHAR(8000))
RETURNS VARCHAR(8000)
AS
BEGIN

	DECLARE	@RESULTADO VARCHAR(8000)

	SET @RESULTADO = ''

	;WITH SPLIT AS
	(
		SELECT 1 AS ID, SUBSTRING(@TEXTO, 1, 1) AS LETRA
		UNION ALL
		SELECT ID + 1, SUBSTRING(@TEXTO, ID + 1, 1)
		FROM SPLIT
		WHERE ID < LEN(@TEXTO)
	)
	SELECT @RESULTADO =@RESULTADO+ (CASE WHEN LETRA LIKE '[A-z0-9]' THEN LETRA ELSE ' ' END)
	FROM SPLIT
	OPTION(MAXRECURSION 0);

	 RETURN @RESULTADO

END
GO


