USE [DB_ADMIX_IN]
GO

/****** Object:  UserDefinedFunction [dbo].[FN_TIRA_CARACTERES_ALFANUMERICOS]    Script Date: 04/11/2014 11:10:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



CREATE FUNCTION [dbo].[FN_TIRA_CARACTERES_ALFANUMERICOS](@NUMERO VARCHAR(255))
RETURNS VARCHAR(255)
AS
BEGIN
	--DECLARE @NUMERO VARCHAR(100)
	DECLARE @RESULT VARCHAR(100)
	DECLARE @POSICAO INT
	DECLARE @TAMANHO INT

	SET @POSICAO = 1
	SET @RESULT = ''

	--SET @NUMERO = 'C&A - BHD 630 SHOPPING DEL REY'

	SET @NUMERO = REPLACE(@NUMERO,'-','')
	SET @NUMERO = REPLACE(@NUMERO,'.','')

	SET @TAMANHO = LEN(@NUMERO)

	WHILE @POSICAO <= @TAMANHO
	BEGIN

		IF ISNUMERIC(SUBSTRING(@NUMERO,@POSICAO,1)) = 1
			BEGIN
				SET @RESULT = @RESULT + SUBSTRING(@NUMERO,@POSICAO,1)
				SET @POSICAO = @POSICAO + 1
			END
			ELSE
				SET @POSICAO = @POSICAO + 1
				
	END

	RETURN @RESULT

END










GO


