USE [ADMIX_CORP]
GO

/****** Object:  UserDefinedFunction [dbo].[VERIFICA_DATA_ADMISSAO_MAIOR_30]    Script Date: 04/11/2014 11:19:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE FUNCTION [dbo].[VERIFICA_DATA_ADMISSAO_MAIOR_30](@MATRICULA VARCHAR(30), @ID_CARGA INT)
RETURNS BIT
AS
BEGIN
	DECLARE @RESULTADO BIT;

	IF(
		SELECT DISTINCT CASE WHEN CONVERT(NUMERIC,GETDATE() - CONVERT(DATETIME,DT_ADMISSAO)) <= 30 THEN 'DENTRO_PRAZO'
		ELSE 'FORA_PRAZO' END
		FROM DB_ADMIX_IN..ADMIX_MOV 
		WHERE ID_LOG_RECEPCAO = @ID_CARGA
		AND CD_MATRICULA = @MATRICULA
	) = 'DENTRO_PRAZO' 
		SET @RESULTADO = 1;
	ELSE
		SET @RESULTADO = 0;

	RETURN @RESULTADO
END

/*
SELECT dbo.[VERIFICA_DATA_VIGENCIA]('00000000000000002545',33362)
AND ID_LOG_RECEPCAO = 33362
AND CD_MATRICULA = '00000000000000002544'

SELECT DISTINCT CASE WHEN DT_ADMISSAO < 30 THEN 'INVALIDO'
ELSE 'CORRETO' END FROM DB_ADMIX_IN..ADMIX_MOV 
WHERE ID_LOG_RECEPCAO = 33362
AND CD_MATRICULA = '00000000000000002545'

SELECT DISTINCT CASE WHEN CONVERT(NUMERIC,GETDATE() - CONVERT(DATETIME,DT_ADMISSAO)) <= 30 THEN 'DENTRO_PRAZO'
ELSE 'FORA_PRAZO' END
FROM DB_ADMIX_IN..ADMIX_MOV 
WHERE ID_LOG_RECEPCAO = 33362
AND CD_MATRICULA = '00000000000000002544'

SELECT CONVERT(DATETIME,DT_ADMISSAO), CONVERT(NUMERIC,GETDATE() - CONVERT(DATETIME,DT_ADMISSAO))
FROM DB_ADMIX_IN..ADMIX_MOV 
WHERE ID_LOG_RECEPCAO = 33362
AND CONVERT(DATETIME,DT_ADMISSAO) > 30

SELECT CONVERT(NUMERIC,GETDATE() - CONVERT(DATETIME,'20090323'))
*/










GO


