USE [ADMIX_CORP]
GO

/****** Object:  UserDefinedFunction [dbo].[VERIFICA_SEXO_IGUAIS]    Script Date: 04/11/2014 11:24:49 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO








CREATE FUNCTION [dbo].[VERIFICA_SEXO_IGUAIS](@MATRICULA VARCHAR(25), @ID INT, @EMPRESA VARCHAR(20), @SUB VARCHAR(20), @OPERADORA VARCHAR(3), @PRODUTO VARCHAR(3))
RETURNS BIT
AS
BEGIN
	DECLARE @RESULTADO BIT;

	IF ((SELECT COUNT(1) FROM DB_ADMIX_IN..ADMIX_MOV WHERE ID_LOG_RECEPCAO = @ID	AND CD_EMPRESA = @EMPRESA AND CD_SUB = @SUB
		AND CD_MATRICULA = @MATRICULA AND CD_PARENTESCO = '00' AND CD_OPERADORA_MOVIMENTACAO = @OPERADORA AND CD_PRODUTO = @PRODUTO) > 2)

		IF ((SELECT COUNT(1) FROM DB_ADMIX_IN..ADMIX_MOV WHERE ID_LOG_RECEPCAO = @ID	AND CD_EMPRESA = @EMPRESA AND CD_SUB = @SUB
				AND CD_MATRICULA = @MATRICULA AND CD_PARENTESCO = '01' AND CD_OPERADORA_MOVIMENTACAO = @OPERADORA AND CD_PRODUTO = @PRODUTO) > 2)

			IF(	(SELECT CD_SEXO FROM DB_ADMIX_IN..ADMIX_MOV 
				WHERE ID_LOG_RECEPCAO = @ID
				AND CD_EMPRESA = @EMPRESA
				AND CD_SUB = @SUB
				AND CD_MATRICULA = @MATRICULA
				AND CD_PARENTESCO = '00'
				AND CD_OPERADORA_MOVIMENTACAO = @OPERADORA 
				AND CD_PRODUTO = @PRODUTO)
				=
				(SELECT CD_SEXO FROM DB_ADMIX_IN..ADMIX_MOV 
				WHERE ID_LOG_RECEPCAO = @ID
				AND CD_EMPRESA = @EMPRESA
				AND CD_SUB = @SUB
				AND CD_MATRICULA = @MATRICULA
				AND CD_PARENTESCO = '01'
				AND CD_OPERADORA_MOVIMENTACAO = @OPERADORA 
				AND CD_PRODUTO = @PRODUTO))
				SET @RESULTADO = 0;
			ELSE
				SET @RESULTADO = 1;

	RETURN @RESULTADO
END

/*
SELECT dbo.VERIFICA_SEXO_IGUAIS('00000000000000002540',33368, 71342, 1)

SELECT * FROM DB_ADMIX_IN..ADMIX_MOV 
WHERE ID_LOG_RECEPCAO = 33368
AND CD_EMPRESA = 71342
AND CD_SUB = 1
AND CD_MATRICULA = '00000000000000002540'

*/















GO


