USE [ADMIX_CORP]
GO

/****** Object:  UserDefinedFunction [dbo].[VERIFICA_DATA_VIGENCIA_MENOR_ADMISSAO]    Script Date: 04/11/2014 11:19:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE FUNCTION [dbo].[VERIFICA_DATA_VIGENCIA_MENOR_ADMISSAO](@MATRICULA VARCHAR(30), @ID_CARGA INT)
RETURNS BIT
AS
BEGIN
	DECLARE @RESULTADO BIT;

	IF(
		SELECT DISTINCT CASE WHEN DT_ADESAO_BENEFICIO < DT_ADMISSAO THEN 'INVALIDO'
		ELSE 'CORRETO' END FROM DB_ADMIX_IN..ADMIX_MOV 
		WHERE ID_LOG_RECEPCAO = @ID_CARGA
		AND CD_MATRICULA = @MATRICULA
	) = 'CORRETO' 
		SET @RESULTADO = 1;
	ELSE
		SET @RESULTADO = 0;

	RETURN @RESULTADO
END

/*
SELECT dbo.[VERIFICA_DATA_VIGENCIA]('00000000000000002545',33362)
AND ID_LOG_RECEPCAO = 33362
AND CD_MATRICULA = '00000000000000002544'

SELECT DISTINCT CASE WHEN DT_ADESAO_BENEFICIO < DT_ADMISSAO THEN 'INVALIDO'
ELSE 'CORRETO' END FROM DB_ADMIX_IN..ADMIX_MOV 
WHERE ID_LOG_RECEPCAO = 33362
AND CD_MATRICULA = '00000000000000002545'
*/









GO


