USE [ADMIX_CORP]
GO

/****** Object:  UserDefinedFunction [dbo].[VERIFICA_NOME_ABREVIADO]    Script Date: 04/11/2014 11:23:07 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


--select [dbo].[VERIFICA_PADRAO_ANS] ('aaAGNESSSE MENEGHETTI POSTIGHER')

-- VERIFICAR A DUPLICIDADE DO CPF
CREATE FUNCTION [dbo].[VERIFICA_NOME_ABREVIADO](@NM_SEGURADO VARCHAR(255))
RETURNS BIT
AS
BEGIN

DECLARE @CONT INT
DECLARE @TAMANHO INT
DECLARE @RETURN BIT

--SETA VARIAVEIS
SET @CONT = 1
SET @RETURN = 1

--RETIRA OS ESPAÇOS DUPLOS
WHILE CHARINDEX('  ', @NM_SEGURADO, 1) > 0
	BEGIN 
		SET @NM_SEGURADO = REPLACE(@NM_SEGURADO, '  ', ' ')
	END	

--COLOCA O NOME MAIUSCULO
SET @NM_SEGURADO = UPPER(@NM_SEGURADO)

--SETA A VARIAVEL COM A QUANTIDADE DE CARACTERES
SET @TAMANHO = LEN(@NM_SEGURADO)

IF @TAMANHO > 0
	BEGIN
		--VERIFICA SE O NOME ESTA ABREVIADO	
		WHILE @CONT <= @TAMANHO
			BEGIN
				IF SUBSTRING(@NM_SEGURADO, @CONT,1) = ' ' AND SUBSTRING(@NM_SEGURADO, @CONT + 2,1) = ' '
					SET @RETURN = 0
				
				IF SUBSTRING(@NM_SEGURADO, @CONT,1) = ' ' AND SUBSTRING(@NM_SEGURADO, @CONT + 3,1) = ' ' AND SUBSTRING(@NM_SEGURADO, @CONT + 1,2) IN ('AP', 'JR')
					SET @RETURN = 0
				
				SET @CONT = @CONT + 1
			END

	END
--PRINT @RETURN
RETURN @RETURN


END
GO


