USE [ADMIX_CORP]
GO

/****** Object:  UserDefinedFunction [dbo].[VERIFICA_DATA_ADMISSAO_DUPLICADA]    Script Date: 04/11/2014 11:18:56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO





CREATE FUNCTION [dbo].[VERIFICA_DATA_ADMISSAO_DUPLICADA](@MATRICULA VARCHAR(30), @ID_CARGA INT)
RETURNS BIT
AS
BEGIN
	DECLARE @RESULTADO BIT;

	IF(	
		SELECT COUNT(1) FROM DB_ADMIX_IN..ADMIX_MOV 
		WHERE ID_LOG_RECEPCAO = @ID_CARGA AND CD_MATRICULA = @MATRICULA
	)=1
		SET @RESULTADO = 1;
	ELSE
		SET @RESULTADO = 0;

	RETURN @RESULTADO
END

/*
SELECT dbo.[VERIFICA_EXISTE_MAIS_VIGENCIAS]('00000000000000002543', 33362)
AND ID_LOG_RECEPCAO = 33362
AND CD_MATRICULA = '00000000000000002544'
*/








GO


