USE [ADMIX_CORP]
GO

/****** Object:  UserDefinedFunction [dbo].[VERIFICA_DUPLICIDADE_PIS]    Script Date: 04/11/2014 11:22:13 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO


-- VERIFICAR A DUPLICIDADE DO PIS
CREATE FUNCTION [dbo].[VERIFICA_DUPLICIDADE_PIS](@PIS VARCHAR(50), @ID_CARGA INT, @OPERADORA VARCHAR(3), @PRODUTO VARCHAR(3))
RETURNS BIT
AS
BEGIN
	DECLARE	@RETURN BIT;

	IF(ISNUMERIC(@PIS)) = 1
		IF(	SELECT COUNT(1)
			FROM DB_ADMIX_IN.dbo.ADMIX_MOV 
			WHERE ID_LOG_RECEPCAO = @ID_CARGA
			AND RIGHT('00' + TP_REGISTRO,2) = '01'
			AND FL_CONSISTENCIA IS NULL
			AND ISNUMERIC(CD_PIS) = 1
			AND RIGHT(REPLICATE('0',12) + LTRIM(RTRIM(CD_PIS)),12) = RIGHT(REPLICATE('0',12) + LTRIM(RTRIM(@PIS)),12)
			AND CD_OPERADORA_MOVIMENTACAO = @OPERADORA
			AND CD_PRODUTO = @PRODUTO
			GROUP BY CD_PIS
			HAVING COUNT(1) > 1
		) > 0
			SET @RETURN=0;
			ELSE 
				SET @RETURN=1;
		ELSE
			SET @RETURN=1;

	RETURN @RETURN;
END 


---SELECT dbo.VERIFICA_DUPLICIDADE_PIS('           ',19329)


--SELECT COUNT(1) FROM DB_ADMIX_IN..ADMIX_MOV WHERE CONVERT(NUMERIC,CD_PIS) = CONVERT(NUMERIC,'12963681854')









GO


