USE [ADMIX_CORP]
GO

/****** Object:  UserDefinedFunction [dbo].[VERIFICA_PARENTESCO_ESTADOCIVIL]    Script Date: 04/11/2014 11:23:48 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO







CREATE FUNCTION [dbo].[VERIFICA_PARENTESCO_ESTADOCIVIL](@MATRICULA VARCHAR(25), @ID BIGINT, @EMPRESA VARCHAR(20), @NOME VARCHAR(255),@DT_NASCIMENTO VARCHAR(10) )
RETURNS BIT
AS
BEGIN
	DECLARE @RESULTADO BIT;

	SELECT @RESULTADO =
	CASE WHEN CD_PARENTESCO = '00' THEN
		CASE WHEN	(SELECT COUNT(1) FROM DB_ADMIX_IN..ADMIX_MOV 
					WHERE ID_LOG_RECEPCAO = @ID
					AND CD_EMPRESA = @EMPRESA 
					AND CD_MATRICULA = @MATRICULA
					AND CD_PARENTESCO = '01') = 1 THEN
					CASE WHEN	(SELECT CD_ESTADO_CIVIL 
								FROM DB_ADMIX_IN..ADMIX_MOV 	
								WHERE ID_LOG_RECEPCAO = @ID
								AND CD_EMPRESA = @EMPRESA
								AND CD_MATRICULA = @MATRICULA
								AND CD_PARENTESCO = '01') = 2 THEN
								1
							ELSE
								2
					END
		END
	WHEN CD_PARENTESCO = '01' THEN
		CASE WHEN CD_ESTADO_CIVIL = 2 THEN 	1 ELSE 0 END
	WHEN CD_PARENTESCO = '06' THEN '1'
	WHEN CD_PARENTESCO = '07' THEN 1
	WHEN CD_PARENTESCO = '08' THEN 1
	WHEN CD_PARENTESCO = '14' THEN 1
	WHEN CD_PARENTESCO = '17' THEN 1
	WHEN CD_PARENTESCO = '18' THEN 1
	WHEN CD_PARENTESCO = '19' THEN 
		CASE WHEN CD_ESTADO_CIVIL = 2 THEN 	1 ELSE 0 END
	WHEN CD_PARENTESCO = '20' THEN 
		CASE WHEN CD_ESTADO_CIVIL = 2 THEN 	1 ELSE 0 END
	ELSE CASE WHEN CD_ESTADO_CIVIL <> 2 THEN 1 ELSE 0 END
	END
	FROM DB_ADMIX_IN..ADMIX_MOV  
	WHERE (1=1)
	AND ID_LOG_RECEPCAO = @ID
	AND CD_EMPRESA = @EMPRESA
	AND CD_MATRICULA = @MATRICULA
	AND NM_SEGURADO =  @NOME
	AND DT_NASCIMENTO =  @DT_NASCIMENTO

	RETURN @RESULTADO
END

/*
SELECT dbo.VERIFICA_PARENTESCO_ESTADOCIVIL('87',39405, '509','CIDALVA ARAUJO PIANCO', '19650626')
*/











GO


