USE [ADMIX_CORP]
GO

/****** Object:  UserDefinedFunction [dbo].[VERIFICA_DEPENDENTE_PORTAL]    Script Date: 04/11/2014 11:20:02 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO



--SELECT dbo.VERIFICA_DEPENDENTE_PORTAL('0001', '71907', '200834', REPLICATE(' ',11), REPLICATE(' ',100), '00000000')


CREATE FUNCTION [dbo].[VERIFICA_DEPENDENTE_PORTAL](@OPERADORA VARCHAR(4),@APOLICE VARCHAR(20), @MATRICULA VARCHAR(20), @CPF VARCHAR(11), @PESSOA VARCHAR(100), @DT_NASCIMENTO VARCHAR(8))
RETURNS BIT
AS
BEGIN
	DECLARE @RESULTADO BIT;

	--REALIZA A PRIMEIRA VALIDAÇÃO (OPERADORA, APOLICE, CPF)
	IF(
		SELECT COUNT(1)
		FROM DW_SA.dbo.SA_SMC_SEGURADO_DEP_PORTAL 
		WHERE (1=1)
		AND CD_OPERADORA_PORTAL	= RIGHT('0000' + LTRIM(RTRIM(@OPERADORA)),4)
		AND	CD_APOLICE	= RIGHT(REPLICATE('0',20) + LTRIM(RTRIM(@APOLICE)), 20) 
		AND CD_CPF = RIGHT(REPLICATE('0',11) + LTRIM(RTRIM(@CPF)),11)
		AND RIGHT(REPLICATE('0',11) + LTRIM(RTRIM(@CPF)),11) <> REPLICATE('0',11)
	)=1
		SET @RESULTADO = 1
		ELSE
			BEGIN
			--CASO NÃO FOI ENCONTRADO NA SEGUNDA VALIDAÇÃO É REALIZADO A TERCEIRA  (OPERADORA, APOLICE, NOME E DATA DE NASCIMENTO)
				IF(
					SELECT COUNT(1)
					FROM DW_SA.dbo.SA_SMC_SEGURADO_DEP_PORTAL 
					WHERE (1=1)
					AND CD_OPERADORA_PORTAL	= RIGHT('0000' + LTRIM(RTRIM(@OPERADORA)),4)
					AND	CD_APOLICE = RIGHT(REPLICATE('0',20) + LTRIM(RTRIM(@APOLICE)), 20) 
					AND (CHARINDEX(' ', LTRIM(RTRIM(@PESSOA)),1) <> 0 AND CHARINDEX(' ', LTRIM(RTRIM(NM_PESSOA)),1) <> 0 AND CHARINDEX(' ', LTRIM(RTRIM(NM_BENEFICIARIO)),1) <> 0 AND 
						(
							LEFT( LTRIM(RTRIM(NM_PESSOA)), CHARINDEX(' ', LTRIM(RTRIM(NM_PESSOA)),1)-1) + LTRIM(RTRIM(RIGHT( LTRIM(RTRIM(NM_PESSOA)), CHARINDEX(' ', REVERSE(LTRIM(RTRIM(NM_PESSOA))),1)))) = LEFT(LTRIM(RTRIM(@PESSOA)), CHARINDEX(' ', LTRIM(RTRIM(@PESSOA)),1)-1) + LTRIM(RTRIM(RIGHT( LTRIM(RTRIM(@PESSOA)), CHARINDEX(' ', REVERSE(LTRIM(RTRIM(@PESSOA))),1))))
							OR
							LEFT( LTRIM(RTRIM(NM_BENEFICIARIO)), CHARINDEX(' ', LTRIM(RTRIM(NM_BENEFICIARIO)),1)-1) + LTRIM(RTRIM(RIGHT( LTRIM(RTRIM(NM_BENEFICIARIO)), CHARINDEX(' ', REVERSE(LTRIM(RTRIM(NM_BENEFICIARIO))),1)))) = LEFT(LTRIM(RTRIM(@PESSOA)), CHARINDEX(' ', LTRIM(RTRIM(@PESSOA)),1)-1) + LTRIM(RTRIM(RIGHT( LTRIM(RTRIM(@PESSOA)), CHARINDEX(' ', REVERSE(LTRIM(RTRIM(@PESSOA))),1))))
						)
					AND DT_NASCIMENTO = ISNULL(@DT_NASCIMENTO,''))
				)>0
					SET @RESULTADO = 1
				ELSE IF(
					SELECT COUNT(1)
					FROM DW_SA.dbo.SA_SMC_SEGURADO_DEP_PORTAL 
					WHERE (1=1)
					AND CD_OPERADORA_PORTAL	= RIGHT('0000' + LTRIM(RTRIM(@OPERADORA)),4)
					AND	CD_APOLICE = RIGHT(REPLICATE('0',20) + LTRIM(RTRIM(@APOLICE)), 20) 
					AND (CHARINDEX(' ', LTRIM(RTRIM(@PESSOA)),1) <> 0 AND CHARINDEX(' ', LTRIM(RTRIM(NM_PESSOA)),1) <> 0 AND CHARINDEX(' ', LTRIM(RTRIM(NM_BENEFICIARIO)),1) <> 0 AND 
						(
							LEFT( LTRIM(RTRIM(NM_PESSOA)), CHARINDEX(' ', LTRIM(RTRIM(NM_PESSOA)),1)-1) + LTRIM(RTRIM(RIGHT( LTRIM(RTRIM(NM_PESSOA)), CHARINDEX(' ', REVERSE(LTRIM(RTRIM(NM_PESSOA))),1)))) = LEFT(LTRIM(RTRIM(@PESSOA)), CHARINDEX(' ', LTRIM(RTRIM(@PESSOA)),1)-1) + LTRIM(RTRIM(RIGHT( LTRIM(RTRIM(@PESSOA)), CHARINDEX(' ', REVERSE(LTRIM(RTRIM(@PESSOA))),1))))
							OR
							LEFT( LTRIM(RTRIM(NM_BENEFICIARIO)), CHARINDEX(' ', LTRIM(RTRIM(NM_BENEFICIARIO)),1)-1) + LTRIM(RTRIM(RIGHT( LTRIM(RTRIM(NM_BENEFICIARIO)), CHARINDEX(' ', REVERSE(LTRIM(RTRIM(NM_BENEFICIARIO))),1)))) = LEFT(LTRIM(RTRIM(@PESSOA)), CHARINDEX(' ', LTRIM(RTRIM(@PESSOA)),1)-1) + LTRIM(RTRIM(RIGHT( LTRIM(RTRIM(@PESSOA)), CHARINDEX(' ', REVERSE(LTRIM(RTRIM(@PESSOA))),1))))
						))
					AND CD_CODIGO_EXTERNO IS NOT NULL
					AND CD_CODIGO_EXTERNO <> '00000000000000000000'
					AND CD_CODIGO_EXTERNO = RIGHT('00000000000000000000' +LTRIM(RTRIM(@MATRICULA)),20)
					
				)>0
					SET @RESULTADO = 1
					ELSE IF(
						SELECT COUNT(1)
						FROM DW_SA.dbo.SA_SMC_SEGURADO_DEP_PORTAL 
						WHERE (1=1)
						AND CD_OPERADORA_PORTAL	= RIGHT('0000' + LTRIM(RTRIM(@OPERADORA)),4)
						AND	CD_APOLICE = RIGHT(REPLICATE('0',20) + LTRIM(RTRIM(@APOLICE)), 20) 
						AND DT_NASCIMENTO = ISNULL(@DT_NASCIMENTO,'')
						AND CD_CODIGO_EXTERNO IS NOT NULL
						AND CD_CODIGO_EXTERNO <> '00000000000000000000'
						AND CD_CODIGO_EXTERNO = RIGHT('00000000000000000000' +LTRIM(RTRIM(@MATRICULA)),20)
						
					)>0
						SET @RESULTADO = 1	
						ELSE
							SET @RESULTADO = 0
			END

	RETURN @RESULTADO
END






GO


