

WITH SOMA_ACUMULADO (SEQ, ID_VENDEDOR, NOME_VENDEDOR, VALOR_VENDA, VALOR_ACUMULADO)  AS
(

  SELECT ROW#, ID_VENDEDOR, NOME_VENDEDOR, [VALOR_VENDA_R$], CAST(INIC.[VALOR_VENDA_R$] AS varchar) 
    FROM (
       SELECT ROW_NUMBER() OVER(PARTITION BY ID_VENDEDOR ORDER BY ID_VENDEDOR, SEQ ASC ) ROW# , ID_VENDEDOR, NOME_VENDEDOR, [VALOR_VENDA_R$]
        FROM TMP_TB_VENDEDOR_RESULT_BKP INIC
  ) INIC
  WHERE INIC.ROW# = 1
  UNION ALL
  SELECT SOMA.ROW#, SOMA.ID_VENDEDOR, SOMA.NOME_VENDEDOR, SOMA.[VALOR_VENDA_R$], CAST(SOMA.[VALOR_VENDA_R$] + CTE.VALOR_VENDA AS varchar)
    FROM (
      SELECT ROW_NUMBER() OVER(PARTITION BY SOMA.ID_VENDEDOR ORDER BY SOMA.ID_VENDEDOR, SOMA.SEQ ASC ) ROW# , SOMA.ID_VENDEDOR, SOMA.NOME_VENDEDOR, SOMA.[VALOR_VENDA_R$] 
        FROM TMP_TB_VENDEDOR_RESULT_BKP SOMA
  ) SOMA
  INNER JOIN SOMA_ACUMULADO CTE
    ON (CTE.SEQ + 1) = SOMA.ROW#
    AND CTE.ID_VENDEDOR = SOMA.ID_VENDEDOR
)

SELECT SEQ, ID_VENDEDOR, NOME_VENDEDOR, VALOR_VENDA, VALOR_ACUMULADO
   FROM SOMA_ACUMULADO 
   ORDER BY 2, 1 asc
   OPTION (MAXRECURSION 0)


   