


IF OBJECT_ID ('tempdb..#TMP_TB_VENDEDOR') IS NOT NULL
BEGIN
DROP TABLE #TMP_TB_VENDEDOR
END

IF OBJECT_ID ('tempdb..#TMP_TB_VENDAS') IS NOT NULL
BEGIN
DROP TABLE #TMP_TB_VENDAS
END

IF OBJECT_ID ('tempdb..#TMP_TB_VENDEDOR_RESULT') IS NOT NULL
BEGIN
DROP TABLE #TMP_TB_VENDEDOR_RESULT
END


 
CREATE TABLE #TMP_TB_VENDEDOR (
	ID_VENDEDOR		INT
	, NM_VENDEDOR	VARCHAR(150)
	, UF_ESTADO		VARCHAR(10)
	, FL_STATUS		VARCHAR(10)
)
INSERT INTO #TMP_TB_VENDEDOR 
SELECT '1','Vendedor 1','SP','0' UNION ALL
SELECT '2','Vendedor 2','SP','0'


CREATE TABLE #TMP_TB_VENDAS (
	ID_VENDA		INT
	, ID_VENDEDOR	INT
	, VL_VENDA		VARCHAR(50)
	, DT_VENDA		DATETIME
)
INSERT INTO #TMP_TB_VENDAS
SELECT 3 , '1', 56.00   , GETDATE() UNION ALL
SELECT 4 , '1', 89.00   , GETDATE() UNION ALL
SELECT 13 ,'1', 167.00  , GETDATE() UNION ALL
SELECT 14 ,'1', 427.00  , GETDATE() UNION ALL
SELECT 33 ,'1', 200.00  , GETDATE() UNION ALL
SELECT 34 ,'1', 375.00  , GETDATE() UNION ALL
SELECT 38 ,'1', 1045.00 , GETDATE() UNION ALL
SELECT 5 , '2', 546.00  , GETDATE() UNION ALL
SELECT 6 , '2', 768.00  , GETDATE() UNION ALL
SELECT 7 , '2', 120.00  , GETDATE()



SELECT   
 ROW_NUMBER() OVER(ORDER BY ID_VENDA ASC) AS SEQ 
,B.ID_VENDEDOR   
,ID_VENDA   
,A.NM_VENDEDOR AS NOME_VENDEDOR   
,VL_VENDA AS VALOR_VENDA_R$   
,CONVERT(NUMERIC(15,2),0.00) AS ACUMULADO   
INTO #TMP_TB_VENDEDOR_RESULT   
FROM #TMP_TB_VENDEDOR A   
INNER JOIN #TMP_TB_VENDAS B   
ON(A.ID_VENDEDOR = B.ID_VENDEDOR)   
WHERE A.FL_STATUS = 0   
ORDER BY 3,1         







DECLARE @ID_VENDEDORES AS TABLE(ID_VENDEDOR INT);
DECLARE @VENDEDORES AS TABLE(SEQ INT);
DECLARE @VALOR_ATUAL AS NUMERIC(15, 2)= 0.00, @ID INT, @ID_VENDEDOR INT;
INSERT INTO @ID_VENDEDORES(ID_VENDEDOR)
       SELECT DISTINCT 
              ID_VENDEDOR
       FROM #TMP_TB_VENDEDOR_RESULT;
WHILE EXISTS
(
    SELECT TOP 1 1
    FROM @ID_VENDEDORES
)
    BEGIN
        SELECT TOP 1 @ID_VENDEDOR = ID_VENDEDOR
        FROM @ID_VENDEDORES
        ORDER BY ID_VENDEDOR ASC;

        SET @VALOR_ATUAL = 0.00;

        INSERT INTO @VENDEDORES(SEQ)
               SELECT SEQ
               FROM #TMP_TB_VENDEDOR_RESULT
               WHERE ID_VENDEDOR = ID_VENDEDOR;

        WHILE EXISTS
        (
            SELECT TOP 1 1
            FROM @VENDEDORES
        )
            BEGIN
			 
			PRINT CONVERT(VARCHAR(255),@ID) + ' ' + CONVERT(VARCHAR(255),@VALOR_ATUAL) + ' ' + CONVERT(VARCHAR(255),@ID_VENDEDOR)

                SELECT TOP 1 @ID = SEQ
                FROM @VENDEDORES
                ORDER BY SEQ ASC;

                SELECT @VALOR_ATUAL = [VALOR_VENDA_R$] + @VALOR_ATUAL
                FROM #TMP_TB_VENDEDOR_RESULT
                WHERE ID_VENDEDOR = @ID_VENDEDOR
                      AND SEQ = @ID;

                UPDATE A
                  SET 
                      A.[ACUMULADO] = @VALOR_ATUAL
                FROM #TMP_TB_VENDEDOR_RESULT A
                WHERE ID_VENDEDOR = @ID_VENDEDOR
                      AND SEQ = @ID;

                DELETE FROM @VENDEDORES
                WHERE @ID = SEQ;

            END;

        DELETE FROM @ID_VENDEDORES
        WHERE ID_VENDEDOR = @ID_VENDEDOR;

    END;

SELECT NOME_VENDEDOR, VALOR_VENDA_R$, ACUMULADO FROM #TMP_TB_VENDEDOR_RESULT ORDER BY RIGHT(NOME_VENDEDOR,2) , SEQ ASC

